export const GET_PIZZAS_REQUEST = "GET_PIZZAS_REQUEST";
export const GET_PIZZAS_SUCCESS = "GET_PIZZAS_SUCCESS";
export const GET_PIZZAS_FAILED = "GET_PIZZAS_FAILED";

export const REGISTERATION_REQUEST_SENT = "REGISTER_REQUEST_SENT";
export const REGISTERATION_SUCCESS = "REGISTER_SUCCESS";
export const REGISTERATION_FAILED = "REGISTERATION_FAILED";

export const LOGIN_REQUEST_SENT = "LOGIN_REQUEST_SENT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const ITEM_TO_CART_SENT = "ITEM_TO_CART_SENT";
export const ITEM_TO_CART_SENT_SUCCESS = "ITEM_TO_CART_SENT_SUCCESS";
export const ITEM_TO_CART_SENT_FAILED = "ITEM_TO_CART_SENT_FAILED";

export const VIEW_CART_DATA_REQUEST_SENT = "VIEW_CART_DATA_REQUEST_SENT";
export const VIEW_CART_DATA_REQUEST_SUCCESS = "VIEW_CART_DATA_REQUEST_SUCCESS";
export const VIEW_CART_DATA_REQUEST_FAILED = "VIEW_CART_DATA_REQUEST_FAILED";

export const DELETE_ITEM_FROM_CART_REQUEST_SENT =
  "DELETE_ITEM_FROM_CART_REQUEST_SENT";
export const DELETE_ITEM_FROM_CART_REQUEST_SUCCESS =
  "DELETE_ITEM_FROM_CART_REQUEST_SUCCESS";
export const DELETE_ITEM_FROM_CART_REQUEST_FAILED =
  "DELETE_ITEM_FROM_CART_REQUEST_FAILED";

export const ITEM_QUANTITY_CHANGE_REQUEST_SENT =
  "ITEM_QUANTITY_CHANGE_REQUEST_SENT";
export const ITEM_QUANTITY_CHANGE_REQUEST_SUCCESS =
  "ITEM_QUANTITY_CHANGE_REQUEST_SUCCESS";
export const ITEM_QUANTITY_CHANGE_REQUEST_FAILED =
  "ITEM_QUANTITY_CHANGE_REQUEST_FAILED";

export const ORDER_PAYMENT_REQUEST_SENT = "ORDER_PAYMENT_REQUEST_SENT";
export const ORDER_PAYMENT_REQUEST_SUCCESS = "ORDER_PAYMENT_REQUEST_SUCCESS";
export const ORDER_PAYMENT_REQUEST_FAILED = "ORDER_PAYMENT_REQUEST_FAILED";
