export const GET_PIZZAS_REQUEST = "GET_PIZZAS_REQUEST";
export const GET_PIZZAS_SUCCESS = "GET_PIZZAS_SUCCESS";
export const GET_PIZZAS_FAILED = "GET_PIZZAS_FAILED";

export const REGISTERATION_REQUEST_SENT = "REGISTER_REQUEST_SENT";
export const REGISTERATION_SUCCESS = "REGISTER_SUCCESS";
export const REGISTERATION_FAILED = "REGISTERATION_FAILED";

export const LOGIN_REQUEST_SENT = "LOGIN_REQUEST_SENT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
